#!/usr/bin/env python2

import McFoo.client
import sys

class McFooClientAddqueue(McFoo.client.McFooClientSimple):
    def __init__(self, pri, backend, media, file):
        McFoo.client.McFooClientSimple.__init__(self)
        self.pri=pri
        self.backend=backend
        self.media=media
        self.file=file

    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.addqueue(self.pri, self.backend, self.media, self.file,
                             McFoo.client.McFooClientExitWhenDone())

def main():
    pri=sys.argv[1]
    pri=int(pri)
    backend=sys.argv[2]
    media=sys.argv[3]
    
    import McFoo.song
    media=McFoo.song.makesafe(media)
    
    file=sys.argv[4]

    c = McFooClientAddqueue(pri, backend, media, file)
    c()

if __name__ == "__main__":
    main()
