#!/usr/bin/env python
import xmlrpc
import os

try:
    host=os.environ['MCFOOHOST']
except KeyError:
    host='localhost'

try:
    port=int(os.environ['MCFOOPORT'])
except KeyError:
    port=25706

c = xmlrpc.client(host, port)

import sys
pri=sys.argv[1]
print  "pri=", pri
pri=int(pri)
backend=sys.argv[2]
media=sys.argv[3]

import sys
sys.path.append('/usr/lib/mc-foo/lib/python')
import McFoo.song
media=McFoo.song.makesafe(media)

file=sys.argv[4]
s=c.execute('mcfoo.addqueue', [pri, backend, media, file])
