#!/usr/bin/env python2.2
#TODO help, usage
#help: "continue - send a continue paused song command to dj"
#usage: "continue"

import McFoo.client
import twisted.internet.main

class McFooClientContinue(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.cont(pbcallback=twisted.internet.main.shutDown)

def main():
    c = McFooClientContinue()
    c()

if __name__ == "__main__":
    main()
