#!/usr/bin/env python2
#TODO help, usage
#help: "continue - send a continue paused song command to dj"
#usage: "continue"

import McFoo.client

class McFooClientContinue(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.cont(McFoo.client.McFooClientExitWhenDone())

def main():
    c = McFooClientContinue()
    c()

if __name__ == "__main__":
    main()
