#!/usr/bin/env python2.2

import McFoo.client
import sys
import twisted.internet.main

class McFooClientDelete(McFoo.client.McFooClientSimple):
    def __init__(self, ids):
        McFoo.client.McFooClientSimple.__init__(self)
        self.ids=ids

    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.delete(self.ids, pbcallback=twisted.internet.main.shutDown)

def main():
    l=map(lambda x: int(x), sys.argv[1:])
    c = McFooClientDelete(l)
    c()

if __name__ == "__main__":
    main()
