#!/usr/bin/env python
import sys
sys.path.append('/usr/lib/mc-foo/lib/python')

import McFoo.playqueue
import McFoo.dj
import McFoo.inputsong
import McFoo.server.xrpc
import asyncore

def main():
    playqueue = McFoo.playqueue.PlayQueue()
    dj = McFoo.dj.Dj()
    inputsong = McFoo.inputsong.InputSong(playqueue)

    XMLRPC = McFoo.server.xrpc.server(dj, playqueue)
    XMLRPC.start_listen()

    while 1:
        if dj.isdone():
            next = playqueue.pop()
            if next==None:
                pass
            else:
                dj.set_next(next)

        if len(playqueue) < 100:
            inputsong.wakeup()
            asyncore.poll(0.001)
        else:
            asyncore.poll(1)

        try:
            XMLRPC.work(0.01)
        except:
            pass

        if McFoo.server.xrpc.stop:
            break

    XMLRPC.close()


if __name__ == "__main__":
    main()
