#!/usr/bin/env python2
import McFoo.client

class McFooClientFan(McFoo.client.McFooClientSimple):
    def __init__(self, TkRoot=None, user=None, password=None,
                 host=None, port=None):
        McFoo.client.McFooClientSimple.__init__(self,
                                                user, password,
                                                host, port)
        self.root=TkRoot

    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        pq = McFoo.gui.playqueue.PlayQueue(self.root, self.remote)
        
        pq.history.listbox.config(selectmode=EXTENDED)
        pq.queue.listbox.config(selectmode=EXTENDED)
        self.root.deiconify()

    def handle_disconnect(self):
        McFoo.client.McFooClientSimple.handle_disconnect(self)
        self.root.quit()

    def handle_loginfailure(self):
        McFoo.client.McFooClientSimple.handle_loginfailure(self)
        self.root.quit()

from Tkinter import *

import McFoo.gui.playqueue
import twisted.internet.tkinternet

import os

def main():
    root = Tk()
    root.withdraw()
    twisted.internet.tkinternet.install(root)
    c = McFooClientFan(TkRoot=root)

    try:
        root.mainloop()
    except KeyboardInterrupt:
        pass

    twisted.internet.tkinternet.stop()

if __name__ == "__main__":
    main()
