#!/usr/bin/env python2.2
#TODO help, usage

import McFoo.client
import sys
import twisted.internet.main

class McFooClientJump(McFoo.client.McFooClientSimple):
    def __init__(self, jump):
        McFoo.client.McFooClientSimple.__init__(self)
        self.jump=jump

    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.jump(jump, pbcallback=twisted.internet.main.shutDown)

def main():
    j=sys.argv[1]
    j=int(j)
    c = McFooClientJump(j)
    c()

if __name__ == "__main__":
    main()
