#!/usr/bin/python
#TODO help, usage
#help: "next - send a skip to next song command to dj"
#usage: "next"

import McFoo.client
import twisted.internet.main

class McFooClientLike(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.like(pbcallback=twisted.internet.main.shutDown)

def main():
    c = McFooClientLike()
    c()

if __name__ == "__main__":
    main()
