#!/usr/bin/env python
import xmlrpc
import os

def main():
    try:
        host=os.environ['MCFOOHOST']
    except KeyError:
        host='localhost'

    try:
        port=int(os.environ['MCFOOPORT'])
    except KeyError:
        port=25706

    c = xmlrpc.client(host, port)

    s=c.execute('mcfoo.list', [])
    for s in s['queue']:
        if s.has_key('id') and s.has_key('backend') \
           and s.has_key('media') and s.has_key('name'):
            print "%-3d %s %s %s" % (s['id'], s['backend'], s['media'], s['name'])

if __name__ == "__main__":
    main()
