#!/usr/bin/python
import McFoo.client
import twisted.internet.main
from errno import EPIPE
import sys

def ShowList(l):
    for s in l:
        if s.has_key('id') and s.has_key('backend') \
           and s.has_key('media') and s.has_key('name'):
            print "%-3d %s %s %s" % (s['id'], s['backend'], s['media'], s['name'])
    twisted.internet.main.shutDown()

class McFooClientList(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.list(pbcallback=ShowList)

def main():
    c = McFooClientList()
    c()

if __name__ == "__main__":
    main()
