#!/usr/bin/env python2
#TODO help, usage
#help: "next - send a skip to next song command to dj"
#usage: "next"

import McFoo.client

class McFooClientNext(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.next(McFoo.client.McFooClientExitWhenDone())

def main():
    c = McFooClientNext()
    c()

if __name__ == "__main__":
    main()
