#!/usr/bin/python
#TODO help, usage
#help: "pause - send a pause command to dj"
#usage: "pause"

import McFoo.client
import twisted.internet.main

class McFooClientPause(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.pause(pbcallback=twisted.internet.main.shutDown)

def main():
    c = McFooClientPause()
    c()

if __name__ == "__main__":
    main()
