#!/usr/bin/env python2
#TODO help, usage
#help: "vol-dec - decrease the volume"
#usage: "vol-dec"

import McFoo.client

class McFooClientVolume_dec(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.volume_dec(callback=McFoo.client.McFooClientExitWhenDone())

def main():
    c = McFooClientVolume_dec()
    c()

if __name__ == "__main__":
    main()
