#!/usr/bin/python
#TODO help, usage
#help: "vol-dec - decrease the volume"
#usage: "vol-dec"

import McFoo.client
import twisted.internet.main

class McFooClientVolume_dec(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.volume_dec(pbcallback=twisted.internet.main.shutDown)

def main():
    c = McFooClientVolume_dec()
    c()

if __name__ == "__main__":
    main()
