#!/usr/bin/env python2.2
#TODO help, usage
#help: "vol-inc - increase the volume"
#usage: "vol-inc"

import McFoo.client
import twisted.internet.main

class McFooClientVolume_inc(McFoo.client.McFooClientSimple):
    def handle_login(self, perspective):
        McFoo.client.McFooClientSimple.handle_login(self, perspective)
        self.remote.volume_inc(pbcallback=twisted.internet.main.shutDown)

def main():
    c = McFooClientVolume_inc()
    c()

if __name__ == "__main__":
    main()
