#!/usr/bin/perl -wT
# & = takes pointer
# % = same file

sub fix(@;) {
  my @r;
  for (@r=@_) {
    s/^[&%]+//;
  }
  return @r;
}

my %labeled = ();
sub label($$;) {
  my ($func, $file) = @_;
  die if $labeled{$func};
  print "    $func [label=\"$func ($file)\"];\n";
}
sub labelsys(@) {
  for (grep {not $labeled{$_}} @_) {
    print "    $_ [label=\"$_ (system)\"];\n";
  }
}

print "digraph g {\n";
print "  rankdir=LR;\n";
print "  subgraph sub {\n";

my %seen;
while (<>) {
  chomp;
  my ($file, $func, $unknown, @calls) = split ' ', $_;
  if ($func =~ /\$/) {
    $func = 'FILE_'.$file;
    $func =~ tr{-/.}{_};
    print "    $func [label=\"Globals in $file\"];\n";
    print join ' ', "    $func -> {", fix(@calls), "};\n";
  } else {
    label($func, $file);
    print join ' ', "    $func -> {", fix(@calls), "};\n";
  }
  for (fix @calls) {
    $seen{$_}=1;    
  }
}

for (keys %seen) {
  labelsys($_);
}

print "  }\n";
print "}\n";
