__all__ = [

    "addqueue",
    "continue",
    "delete",
    "fan",
    "jump",
    "like",
    "list",
    "monitor",
    "next",
    "pause",
    "pauseorplay",
    "vol-dec",
    "vol-inc",
    "mousecontrol",
    "getscores",
    "getwriteprofiles",
    "setwriteprofiles",
    "getreadprofiles",
    "setreadprofiles",
    "hate",
    "dislike",
    ]
