#!/usr/bin/perl -w
use strict;
use CDB_File;

use vars qw($MCFOOHOME $MCFOODATA $MCFOOCACHE);

$MCFOOHOME=$ENV{MCFOOHOME} || '/usr/lib/mc_foo';
$MCFOODATA=$ENV{MCFOODATA} || '/var/lib/mc_foo';
$MCFOOCACHE=$ENV{MCFOOCACHE} || '/var/cache/mc_foo';

sub fail(@) {
  warn("remember-profiles: @_\n");
  exit(1);
}

sub usage() {
  warn("remember-profiles: usage:\n",
       "  remember-profiles profile-name\n");
  exit(1);
}

usage() if @ARGV!=1;
my ($profile) = @ARGV;

my %new;
if (-e "$MCFOODATA/profiles/$profile.cdb") {
  my %old;
  tie %old, 'CDB_File', "$MCFOODATA/profiles/$profile.cdb"
    or fail "open old profile: $!";
  %new=%old;
  untie %old;
}

my $clean_end;
while(<STDIN>) {
  chomp;
  $clean_end=1, last if /^$/;
  /^([+-]?\d+)\s+(.*)/ or fail "invalid input data: $_";
  my ($var, $val) = ("score:$2", $1);
  defined $val or fail "invalid fields in input data: $_";
  if (defined $new{$var}) {
    $new{$var}+=$val;
  } else {
    $new{$var}=$val;
  }
}

$clean_end or fail 'stdin did not end with an empty line';

CDB_File::create %new, "$MCFOODATA/profiles/$profile.cdb", 
  "$MCFOODATA/profiles/$profile.$$.tmp"
  or fail "unable to create new profile: $!";

exit(0);
