#!/usr/bin/env python2
import McFoo.turntable

def main():
    p=McFoo.turntable.Turntable()
    try:
        p.loop()
    except KeyboardInterrupt:
        pass

if __name__ == "__main__":
    main()
