#!/usr/bin/env python
import sys
sys.path.append('/usr/lib/mc-foo/lib/python')

import McFoo.turntable

def main():
    p=McFoo.turntable.Turntable()
    p.loop()

if __name__ == "__main__":
    main()
